- name: Setup editing environment
  hosts: localhost
  become: false
  gather_facts: false

  vars_files:
    - vars.yml
    - bashrc.yml

  tasks:

    - name: Ensure needed python packages are installed
      ansible.builtin.pip:
        name: yamllint
        state: present
        extra_args: --user

    - name: Ensure needed directories are present
      loop: "{{ dir_list }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory

    - name: Ensure pathogen is downloaded
      ansible.builtin.get_url:
        url: https://tpo.pe/pathogen.vim
        dest: ~/.vim/autoload/pathogen.vim

    - name: Ensure plugin repos are cloned
      loop: "{{ repo_list }}"
      ansible.builtin.git:
        repo: "{{ item }}"
        dest: ~/.vim/bundle/{{ item.split('/')[-1] | regex_replace('\.git$') }}

    - name: Ensure config files are copied
      loop: "{{ lookup('dict', config_files) }}"
      notify: Ensure terminal terminates
      ansible.builtin.copy:
        src: "{{ item['value']['file'] }}"
        dest: "{{ item['value']['dest'] }}"

    - name: Ensure ~/.bashrc is configured
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        block: "{{ my_bashrc }}"

    - name: Ensure resolution is obtained
      register: current_resolution
      ansible.builtin.command: xrandr
          
    - name: Ensure resolution is set
      when: "'1920x1080' not in current_resolution.stdout_lines"
      ansible.builtin.command: xrandr --size 1920x1080

    - name: Render terminal profile template
      notify: Ensure dconf loads terminal profile
      ansible.general.template:
        src: terminal_profile.j2
        dest: /var/tmp/terminal_profile
        mode: 0644


  handlers:

    - name: Ensure terminal terminates
      ansible.builtin.command: |
        killall gnome-terminal-server

    - name: Ensure terminal profile is slurped
      listen: Ensure dconf loads terminal profile
      register: terminal_profile
      ansible.builtin.slurp:
        src: /var/tmp/terminal_profile

    - name: debug
      listen: Ensure dconf loads terminal profile
      debug:
        var: terminal_profile

    - name: Ensure profile is loaded
      listen: Ensure dconf loads terminal profile
      community.general.system.dconf:
        key: /org/gnome/terminal/
        value: "{{ terminal_profile.stdout }}"
        state: present