- name: Setup editing environment
  hosts: localhost
  become: false
  gather_facts: false

  vars_files:
    - vars.yml
    - bashrc.yml

  tasks:

    - name: Ensure needed python packages are installed
      pip:
        name: yamllint
        state: present
        extra_args: --user

    - name: Ensure needed directories are present
      loop: "{{ dir_list }}"
      file:
        path: "{{ item }}"
        state: directory

    - name: Ensure pathogen is downloaded
      get_url:
        url: https://tpo.pe/pathogen.vim
        dest: ~/.vim/autoload/pathogen.vim

    - name: Ensure plugin repos are cloned
      loop: "{{ repo_list }}"
      git:
        repo: "{{ item }}"
        dest: ~/.vim/bundle/{{ item.split('/')[-1] | regex_replace('\.git$') }}

    - name: Ensure config files are copied
      loop: "{{ lookup('dict', config_files) }}"
      copy:
        src: "{{ item['value']['file'] }}"
        dest: "{{ item['value']['dest'] }}"

    - name: Ensure ~/.bashrc is configured
      blockinfile:
        path: ~/.bashrc
        block: "{{ my_bashrc }}"
          
    - name: Ensure resolution is set
      command: xrandr --size 1920x1080

    - name: Ensure terminal terminates
      command: |
        killall gnome-terminal-server
